# Generated by Django 3.1.3 on 2021-01-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
